### ISSUE TITLE
Не валидирует поля, у которых disabled="disabled" изначально

### ISSUE THREAD

**Issue by Golden-Puma** [artlebedev/expromptum#17]
Есть форма, в которой некоторые поля изначально скрыты и disabled, т.е. они могут понадоится, а могут и нет. 
Прописываем у них атрибут data-xp="required: true". Но когда эти поля нужны, скриптом снимается атрибут disabled/ Но поле больше не хочет уже валидироваться. Как быть? как запустить expromptum у таких полей?

**Comment by vlalek** [comment]
Если снять disabled скриптом через expromptum, то все будет работать, как надо.
Пример:
xP('input[name=some]').first().disable(false)

**Comment by Golden-Puma** [comment]
СПАСИБО!
